image: gitlab-registry.imt-atlantique.fr/ue-scale/currency-converter/node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install --save-dev jest jest-junit
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 10 days
    when: on_success
    paths:
      - node_modules/

run_test:
  stage: test
  dependencies:
    - build
  script:
    - npm test
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml


pages:
  stage: deploy
  script:
  - mkdir public
  - cp pokemon.html public/
  - cp filter.js public/
  - cp pokemonProvider.js public/
  - cp showPokemon.js public/
  artifacts:
    paths:
    - public
